name: t
favicon: null
layout_spectrum: 0.8938324879854918
typography_spectrum: 0.10642033210024238
title: URORDER
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7667784735094756
  lightness: 0.2070810911245644
  saturation: 0.13230027514509857
  rhythmicContrast: 0.46054954710416496
purpose: []
